//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileManager.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory to change..
        /// </summary>
        public static string cdDir {
            get {
                return ResourceManager.GetString("cdDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command changes the working directory..
        /// </summary>
        public static string cmdCd {
            get {
                return ResourceManager.GetString("cmdCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command changes the foreground color of the console (or, if not specified, shows all console colors)..
        /// </summary>
        public static string cmdColor {
            get {
                return ResourceManager.GetString("cmdColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command copies file from one place to another (and overwrites the old file it if specified)..
        /// </summary>
        public static string cmdCopy {
            get {
                return ResourceManager.GetString("cmdCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command deletes a file..
        /// </summary>
        public static string cmdDelFile {
            get {
                return ResourceManager.GetString("cmdDelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command scans directory for files and/or directories..
        /// </summary>
        public static string cmdDir {
            get {
                return ResourceManager.GetString("cmdDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command changes the disk if specified, otherwise displays the list of all disks..
        /// </summary>
        public static string cmdDisk {
            get {
                return ResourceManager.GetString("cmdDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command moves file from one place to another (and overwrites the old file it if specified)..
        /// </summary>
        public static string cmdMove {
            get {
                return ResourceManager.GetString("cmdMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command creates a new file (and fills it with content in some encoding if specified)..
        /// </summary>
        public static string cmdNewFile {
            get {
                return ResourceManager.GetString("cmdNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command prints content of one (or more files) to console with default (or specified) encoding..
        /// </summary>
        public static string cmdPrint {
            get {
                return ResourceManager.GetString("cmdPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color to specify (optional)..
        /// </summary>
        public static string colorColor {
            get {
                return ResourceManager.GetString("colorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding (either Default, UTF8, ASCII or Unicode)..
        /// </summary>
        public static string commonEncoding {
            get {
                return ResourceManager.GetString("commonEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to overwrite the file..
        /// </summary>
        public static string commonFileOverwrite {
            get {
                return ResourceManager.GetString("commonFileOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from file path..
        /// </summary>
        public static string copyFrom {
            get {
                return ResourceManager.GetString("copyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to file path..
        /// </summary>
        public static string copyTo {
            get {
                return ResourceManager.GetString("copyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEBUG].
        /// </summary>
        public static string debuggerPrefix {
            get {
                return ResourceManager.GetString("debuggerPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to delete..
        /// </summary>
        public static string delFileFile {
            get {
                return ResourceManager.GetString("delFileFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory to scan (optional)..
        /// </summary>
        public static string dirDir {
            get {
                return ResourceManager.GetString("dirDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories:.
        /// </summary>
        public static string dirDirectories {
            get {
                return ResourceManager.GetString("dirDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        public static string dirFiles {
            get {
                return ResourceManager.GetString("dirFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide directories..
        /// </summary>
        public static string dirHideDirs {
            get {
                return ResourceManager.GetString("dirHideDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide files..
        /// </summary>
        public static string dirHideFiles {
            get {
                return ResourceManager.GetString("dirHideFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk to set (either its ID or name)..
        /// </summary>
        public static string diskDisk {
            get {
                return ResourceManager.GetString("diskDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color {0} is out of bounds..
        /// </summary>
        public static string errColorBounds {
            get {
                return ResourceManager.GetString("errColorBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This directory doesn&apos;t exist..
        /// </summary>
        public static string errCommonDirNotExists {
            get {
                return ResourceManager.GetString("errCommonDirNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; exists..
        /// </summary>
        public static string errCommonFileExists {
            get {
                return ResourceManager.GetString("errCommonFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; doesn&apos;t exist..
        /// </summary>
        public static string errCommonFileNotExists {
            get {
                return ResourceManager.GetString("errCommonFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the disk with name &quot;{0}&quot;..
        /// </summary>
        public static string errDiskInvalidName {
            get {
                return ResourceManager.GetString("errDiskInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the disk with number {0}..
        /// </summary>
        public static string errDiskInvalidNumber {
            get {
                return ResourceManager.GetString("errDiskInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;{0}&quot; is not recognized. Use &quot;help&quot; command..
        /// </summary>
        public static string errTerminalBadCommand {
            get {
                return ResourceManager.GetString("errTerminalBadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;--version&quot; option is invalid in this context..
        /// </summary>
        public static string errTerminalVersionAsOption {
            get {
                return ResourceManager.GetString("errTerminalVersionAsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR].
        /// </summary>
        public static string loggerErrorPrefix {
            get {
                return ResourceManager.GetString("loggerErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SUCCESS].
        /// </summary>
        public static string loggerSuccessPrefix {
            get {
                return ResourceManager.GetString("loggerSuccessPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move from file path..
        /// </summary>
        public static string moveFrom {
            get {
                return ResourceManager.GetString("moveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to file path..
        /// </summary>
        public static string moveTo {
            get {
                return ResourceManager.GetString("moveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to create..
        /// </summary>
        public static string newFileFile {
            get {
                return ResourceManager.GetString("newFileFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines to write to a new file..
        /// </summary>
        public static string newFileLines {
            get {
                return ResourceManager.GetString("newFileLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to overwrite the file if it exists..
        /// </summary>
        public static string newFileOverwrite {
            get {
                return ResourceManager.GetString("newFileOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to print..
        /// </summary>
        public static string printFiles {
            get {
                return ResourceManager.GetString("printFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppresses summary message and stops executing after the command completes..
        /// </summary>
        public static string quiteQuite {
            get {
                return ResourceManager.GetString("quiteQuite", resourceCulture);
            }
        }
    }
}
