//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terminal.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory to change..
        /// </summary>
        public static string cdDir {
            get {
                return ResourceManager.GetString("cdDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command changes the working directory..
        /// </summary>
        public static string cmdCd {
            get {
                return ResourceManager.GetString("cmdCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command clears the console..
        /// </summary>
        public static string cmdClear {
            get {
                return ResourceManager.GetString("cmdClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command changes the foreground color of the console (or, if not specified, shows all console colors)..
        /// </summary>
        public static string cmdColor {
            get {
                return ResourceManager.GetString("cmdColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command copies file from one place to another (and overwrites the old file it if specified)..
        /// </summary>
        public static string cmdCopy {
            get {
                return ResourceManager.GetString("cmdCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command deletes a file..
        /// </summary>
        public static string cmdDelFile {
            get {
                return ResourceManager.GetString("cmdDelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command scans directory for files and/or directories..
        /// </summary>
        public static string cmdDir {
            get {
                return ResourceManager.GetString("cmdDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command changes the disk if specified, otherwise displays the list of all disks..
        /// </summary>
        public static string cmdDisk {
            get {
                return ResourceManager.GetString("cmdDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command terminates the program..
        /// </summary>
        public static string cmdExit {
            get {
                return ResourceManager.GetString("cmdExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command prints the hash sums of files..
        /// </summary>
        public static string cmdHash {
            get {
                return ResourceManager.GetString("cmdHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command creates a directory with the specified path..
        /// </summary>
        public static string cmdMkdir {
            get {
                return ResourceManager.GetString("cmdMkdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command moves file from one place to another (and overwrites the old file it if specified)..
        /// </summary>
        public static string cmdMove {
            get {
                return ResourceManager.GetString("cmdMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command prints content of one (or more files) to console with default (or specified) encoding..
        /// </summary>
        public static string cmdPrint {
            get {
                return ResourceManager.GetString("cmdPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command removes the directory with the specified path..
        /// </summary>
        public static string cmdRmdir {
            get {
                return ResourceManager.GetString("cmdRmdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command creates a new file and fills it with content in some encoding if specified. If the file existed and overwrite option was specified, overwrites it. If the file existed and append option was specified, appends to it..
        /// </summary>
        public static string cmdWriteFile {
            get {
                return ResourceManager.GetString("cmdWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color to specify (optional)..
        /// </summary>
        public static string colorColor {
            get {
                return ResourceManager.GetString("colorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset color to default..
        /// </summary>
        public static string colorReset {
            get {
                return ResourceManager.GetString("colorReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding (either Default, UTF8, ASCII or Unicode)..
        /// </summary>
        public static string commonEncoding {
            get {
                return ResourceManager.GetString("commonEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to overwrite the file if it exists..
        /// </summary>
        public static string commonFileOverwrite {
            get {
                return ResourceManager.GetString("commonFileOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from file path..
        /// </summary>
        public static string copyFrom {
            get {
                return ResourceManager.GetString("copyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to file path..
        /// </summary>
        public static string copyTo {
            get {
                return ResourceManager.GetString("copyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEBUG].
        /// </summary>
        public static string debuggerPrefix {
            get {
                return ResourceManager.GetString("debuggerPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to delete..
        /// </summary>
        public static string delFileFile {
            get {
                return ResourceManager.GetString("delFileFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change time.
        /// </summary>
        public static string dirChangeTime {
            get {
                return ResourceManager.GetString("dirChangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creation time.
        /// </summary>
        public static string dirCreationTime {
            get {
                return ResourceManager.GetString("dirCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory to scan (optional)..
        /// </summary>
        public static string dirDir {
            get {
                return ResourceManager.GetString("dirDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories:.
        /// </summary>
        public static string dirDirectories {
            get {
                return ResourceManager.GetString("dirDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        public static string dirFiles {
            get {
                return ResourceManager.GetString("dirFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide directories..
        /// </summary>
        public static string dirHideDirs {
            get {
                return ResourceManager.GetString("dirHideDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide files..
        /// </summary>
        public static string dirHideFiles {
            get {
                return ResourceManager.GetString("dirHideFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string dirName {
            get {
                return ResourceManager.GetString("dirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size (bytes).
        /// </summary>
        public static string dirSizeBytes {
            get {
                return ResourceManager.GetString("dirSizeBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk to set (either its ID or name)..
        /// </summary>
        public static string diskDisk {
            get {
                return ResourceManager.GetString("diskDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All disks:.
        /// </summary>
        public static string diskDisks {
            get {
                return ResourceManager.GetString("diskDisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format.
        /// </summary>
        public static string diskFormat {
            get {
                return ResourceManager.GetString("diskFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free space (bytes).
        /// </summary>
        public static string diskFreeSpace {
            get {
                return ResourceManager.GetString("diskFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string diskID {
            get {
                return ResourceManager.GetString("diskID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label.
        /// </summary>
        public static string diskLabel {
            get {
                return ResourceManager.GetString("diskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string diskName {
            get {
                return ResourceManager.GetString("diskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No label.
        /// </summary>
        public static string diskNoLabel {
            get {
                return ResourceManager.GetString("diskNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total size (bytes).
        /// </summary>
        public static string diskTotalSize {
            get {
                return ResourceManager.GetString("diskTotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color {0} is out of bounds..
        /// </summary>
        public static string errColorBounds {
            get {
                return ResourceManager.GetString("errColorBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This directory already exists..
        /// </summary>
        public static string errCommonDirExists {
            get {
                return ResourceManager.GetString("errCommonDirExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This directory doesn&apos;t exist..
        /// </summary>
        public static string errCommonDirNotExists {
            get {
                return ResourceManager.GetString("errCommonDirNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; exists..
        /// </summary>
        public static string errCommonFileExists {
            get {
                return ResourceManager.GetString("errCommonFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; doesn&apos;t exist..
        /// </summary>
        public static string errCommonFileNotExists {
            get {
                return ResourceManager.GetString("errCommonFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the disk with name &quot;{0}&quot;..
        /// </summary>
        public static string errDiskInvalidName {
            get {
                return ResourceManager.GetString("errDiskInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the disk with number {0}..
        /// </summary>
        public static string errDiskInvalidNumber {
            get {
                return ResourceManager.GetString("errDiskInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;{0}&quot; is not recognized. Use &quot;help&quot; command..
        /// </summary>
        public static string errTerminalBadCommand {
            get {
                return ResourceManager.GetString("errTerminalBadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;--version&quot; option is invalid in this context..
        /// </summary>
        public static string errTerminalVersionAsOption {
            get {
                return ResourceManager.GetString("errTerminalVersionAsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options &quot;overwrite&quot; and &quot;append&quot; cannot be specified at the same time..
        /// </summary>
        public static string errWriteFileOverwriteAndAppend {
            get {
                return ResourceManager.GetString("errWriteFileOverwriteAndAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advanced scenario.
        /// </summary>
        public static string exampleAdvanced {
            get {
                return ResourceManager.GetString("exampleAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to common scenario.
        /// </summary>
        public static string exampleCommon {
            get {
                return ResourceManager.GetString("exampleCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiline scenario.
        /// </summary>
        public static string exampleMultiline {
            get {
                return ResourceManager.GetString("exampleMultiline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashing algorithm (either MD5, SHA1, SHA256, SHA384 or SHA512)..
        /// </summary>
        public static string hashAlgo {
            get {
                return ResourceManager.GetString("hashAlgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to calculate hashes..
        /// </summary>
        public static string hashFiles {
            get {
                return ResourceManager.GetString("hashFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR].
        /// </summary>
        public static string loggerErrorPrefix {
            get {
                return ResourceManager.GetString("loggerErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SUCCESS].
        /// </summary>
        public static string loggerSuccessPrefix {
            get {
                return ResourceManager.GetString("loggerSuccessPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory to create..
        /// </summary>
        public static string mkdirDir {
            get {
                return ResourceManager.GetString("mkdirDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move from file path..
        /// </summary>
        public static string moveFrom {
            get {
                return ResourceManager.GetString("moveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to file path..
        /// </summary>
        public static string moveTo {
            get {
                return ResourceManager.GetString("moveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to print..
        /// </summary>
        public static string printFiles {
            get {
                return ResourceManager.GetString("printFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppresses summary message and stops executing after the command completes..
        /// </summary>
        public static string quiteQuite {
            get {
                return ResourceManager.GetString("quiteQuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory to remove..
        /// </summary>
        public static string rmdirDir {
            get {
                return ResourceManager.GetString("rmdirDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to append to the file if it exists..
        /// </summary>
        public static string writeFileAppend {
            get {
                return ResourceManager.GetString("writeFileAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to create (rewrite)..
        /// </summary>
        public static string writeFileFile {
            get {
                return ResourceManager.GetString("writeFileFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines to write to a new (existing) file..
        /// </summary>
        public static string writeFileLines {
            get {
                return ResourceManager.GetString("writeFileLines", resourceCulture);
            }
        }
    }
}
